### ISSUE TITLE
Question about SparkSQL

### ISSUE THREAD

**Issue by WithLittleStress** [thustorage/lambda-io#2]
Hi,

I read your paper and it was an interesting paper!

In the evaluations section, the paper mentions your work about porting Spark SQL to λ-IO and running evaluations.
By any chance, do you have plans on opening the ported Spark SQL code?

**Comment by yzim** [comment]
Thanks for your interest! Due to the time limit, we modified Spark SQL and HDFS for specific queries and datasets by *hard coding*. I am afraid that the code is not general to fit your requirements. We described the core idea in our paper, "for an SQL query, Spark SQL first parses the query, constructs JAVA source code for processing data...". We extracted processing logic (row/column filter) in the JAVA source code and integrated it into the HDFS's logic of reading the dataset file.

I highly recommend that you try to modify the source code of Spark SQL and HDFS. We may open the source code modified for one specific query as an example in the future.
